service: serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: 'dev'

functions:
  auth:
    handler: handler.auth
    events:
      - http:
          path: auth/login
          method: post
  product:
    handler: handler.product
    events:
      - http:
          path: products
          method: get
      - http:
          path: products
          method: post
