service: serverless-api

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: 'dev'

functions:
  product:
    handler: handler.product
    events:
      - http:
          path: products
          method: get
  user:
    handler: handler.user
    events:
      - http:
          path: users
          method: get
